#!/bin/bash
#
# An implementation of PsyMed/10/SOP122/v1.1, section 6.4 onwards using
# the PennCNV software to call CNVs in data 
# generated by Illumina iScan array genotyping. Much of this is built on scripts by Ellis Piers
# Modifications added by Peter Richardson
#SBATCH --job-name=penncnvcalling
#SBATCH --account=scw1354
#SBATCH --partition=c_compute_neuro1
#SBATCH --time=00-12:00:00
#SBATCH --mem-per-cpu=10G
#SBATCH --cpus-per-task=4
#SBATCH --output=logs/o.%J
#SBATCH --error=logs/e.%J

set -euo pipefail
# ==============================================================================
# CONFIGURATION AND SETUP
# ==============================================================================

# Validate command line arguments
if [ $# -lt 1 ]; then
    echo "ERROR: Missing required input file argument" >&2
    echo "Usage: $0 <input_file> [config_file]" >&2
    exit 1
fi

INPUT_FILE="$1"
CONFIG_FILE="${2:-penncnv_config.yaml}"

# Validate input files exist
if [ ! -f "$INPUT_FILE" ]; then
    echo "ERROR: Input file not found: $INPUT_FILE" >&2
    exit 1
fi

if [ ! -f "$CONFIG_FILE" ]; then
    echo "ERROR: Config file not found: $CONFIG_FILE" >&2
    exit 1
fi

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PENN_CNV_FILES_DIR="${SCRIPT_DIR}/penn_cnv_files"

# ==============================================================================
# HELPER FUNCTIONS
# ==============================================================================

# Function to validate exactly one file exists
validate_single_file() {
    local pattern=$1
    local description=$2
    local files=("$PENN_CNV_FILES_DIR"/$pattern)
    
    if (( ${#files[@]} == 0 )); then
        echo "ERROR: No $description file found in $PENN_CNV_FILES_DIR" >&2
        exit 1
    elif (( ${#files[@]} > 1 )); then
        echo "ERROR: Multiple $description files found in $PENN_CNV_FILES_DIR" >&2
        printf '  %s\n' "${files[@]}" >&2
        exit 1
    fi
    
    # Return the single file found
    echo "${files[0]}"
}


# Logging functions
log_message() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $1" | tee -a "$MAIN_LOG"
}

log_error() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] ERROR: $1" | tee -a "$MAIN_LOG" >&2
}

# ==============================================================================
# VALIDATE REQUIRED FILES
# ==============================================================================

PFB_FILE=$(validate_single_file "*.pfb" ".pfb")
GCM_FILE=$(validate_single_file "*.gcmodel" ".gcmodel")
MASTER_LIST=$(validate_single_file "master_list.txt" "master list")

# ==============================================================================
# SETUP DIRECTORY STRUCTURE
# ==============================================================================

SAMPLE_PREFIX=$(basename "$INPUT_FILE" | sed 's/\(.*\)\..*/\1/')
SCRATCH_BASE="/scratch/${USER}"

# Handle non-HPC environments
if [ ! -d "$SCRATCH_BASE" ]; then 
    echo "WARNING: /scratch not found, using temp local directory instead" >&2
    SCRATCH_BASE="$(pwd)/tmp_scratch"
    mkdir -p "$SCRATCH_BASE"
fi

BASE_DIR="${SCRATCH_BASE}/${SAMPLE_PREFIX}"
OUTPUT_DIR="${BASE_DIR}/output"
RAW_CNVS_DIR="${OUTPUT_DIR}/raw_cnvs"
CLEAN_CNVS_DIR="${OUTPUT_DIR}/clean_cnvs"
QC_CNVS_DIR="${OUTPUT_DIR}/qc_cnvs"
SPLIT_FILES_DIR="${OUTPUT_DIR}/split_files"
LOGS_DIR="${OUTPUT_DIR}/logs"

mkdir -p "$RAW_CNVS_DIR" "$CLEAN_CNVS_DIR" "$QC_CNVS_DIR" "$SPLIT_FILES_DIR" "$LOGS_DIR"


# ==============================================================================
# LOAD MODULES AND ENVIRONMENT
# ==============================================================================

if command -v module >/dev/null 2>&1; then
    module load penncnv 2>/dev/null || true
    module load R 2>/dev/null || true
    module load anaconda 2>/dev/null || true
    module load python 2>/dev/null || true
else
    # Fallback for local installations
    export PATH="$HOME/penncnv:$HOME/miniconda3/bin:$PATH"
fi

# Parse configuration file
eval "$(python3 parse_config.py "$CONFIG_FILE")"


# ==============================================================================
# INITIALIZE LOGGING
# ==============================================================================

MAIN_LOG="${LOGS_DIR}/${SAMPLE_PREFIX}_pipeline.log"
PENNCNV_LOG="${LOGS_DIR}/${SAMPLE_PREFIX}_penncnv.log"
RAW_CNV_OUT="${RAW_CNVS_DIR}/${SAMPLE_PREFIX}.rawcnv"

log_message "=============================="
log_message "=== Starting PennCNV Pipeline for ${SAMPLE_PREFIX} ==="
log_message "=============================="
log_message "Input file: $INPUT_FILE"
log_message "PFB file: $PFB_FILE"
log_message "GCM file: $GCM_FILE"
log_message "Master list: $MASTER_LIST"
log_message "Config file: $CONFIG_FILE"
log_message "Output directory: $OUTPUT_DIR"

# ==============================================================================
# STEP 1: SPLIT INPUT FILES
# ==============================================================================


log_message "Step 1: Splitting input files"

# Clean up any previous split files
rm -f "${SPLIT_FILES_DIR}/${SAMPLE_PREFIX}."*

if ! kcolumn.pl \
    "$INPUT_FILE" \
    split 3 \
    -heading 3 \
    -name_by_header \
    -tab \
    -output "${SPLIT_FILES_DIR}/${SAMPLE_PREFIX}"; then 
    log_error "File splitting failed"
    exit 1 
fi

log_message "File splitting complete"


# ==============================================================================
# STEP 2: DETECT RAW CNVs
# ==============================================================================


log_message "Step 2: Detecting raw CNVs..."

HMM_FILE="$(dirname `which detect_cnv.pl`)/lib/hhall.hmm"


if [ ! -f "$HMM_FILE" ]; then
    log_error "HMM file not found: $HMM_FILE"
    exit 1
fi

# Change to base directory for PennCNV execution
cd "$BASE_DIR" || exit 1

if ! detect_cnv.pl \
    -test \
    -confidence \
    -hmm "$HMM_FILE" \
    -pfb "$PFB_FILE" \
    -gcmodel "$GCM_FILE" \
    -log "$PENNCNV_LOG" \
    "${SPLIT_FILES_DIR}/${SAMPLE_PREFIX}."* \
    -output "$RAW_CNV_OUT" \
    >>"$PENNCNV_LOG" 2>&1; then
    log_error "Raw CNV detection failed"
    cd "$SCRIPT_DIR" || exit 1
    exit 1
fi

cd "$SCRIPT_DIR" || exit 1
log_message "Raw CNV detection complete"

# ==============================================================================
# STEP 3: CLEAN AND MERGE CNVs
# ==============================================================================

log_message "Step 3: Cleaning and merging CNVs"

if ! clean_cnv.pl \
    combineseg "$RAW_CNV_OUT" \
    -bp \
    -signalfile "$PFB_FILE" \
    -output "${CLEAN_CNVS_DIR}/${SAMPLE_PREFIX}.clean.rawcnv"; then
    log_error "CNV cleaning and merging failed"
    exit 1
fi

log_message "Cleaning and merging complete"

# ==============================================================================
# STEP 4: QUALITY CONTROL FILTERING
# ==============================================================================

log_message "Step 4: Applying quality control filters"

if ! filter_cnv.pl \
    "${CLEAN_CNVS_DIR}/${SAMPLE_PREFIX}.clean.rawcnv" \
    -numsnp 10 \
    -length 100k \
    -qclrrsd 0.3 \
    -qclogfile "$PENNCNV_LOG" \
    -qcpassout "${QC_CNVS_DIR}/${SAMPLE_PREFIX}.qcpass" \
    -qcsumout "${QC_CNVS_DIR}/${SAMPLE_PREFIX}.qcsum" \
    -output "${QC_CNVS_DIR}/${SAMPLE_PREFIX}.goodcnv"; then
    log_error "Quality control filtering failed"
    exit 1
fi

log_message "Quality control complete"

# ==============================================================================
# PIPELINE COMPLETE
# ==============================================================================

log_message "=============================="
log_message "=== Pipeline completed successfully for ${SAMPLE_PREFIX} ==="
log_message "=============================="
log_message "Results available in: $OUTPUT_DIR"